### PR TITLE
added userid route

### PR DESCRIPTION
**Pull request by dhruvdabhi101**
Closes issue no #15 
Please review and merge.

### CODE REVIEW

**Comment by sanyamjain04** [comment]
@dhruvdabhi101 Can you tell what is the response we are sending to the client when the request is successful and when is not?
Maybe the Screenshot of the response help?

**Comment by dhruvdabhi101** [comment]
Screenshot 2022-10-22 at 2 26 33 PM

This is the response I'm getting after the request.

**Comment by sanyamjain04** [comment]
@dhruvdabhi101 And when the user enters the wrong username what is the response?

**Comment by dhruvdabhi101** [comment]
Screenshot 2022-10-22 at 2 30 29 PM
This is what i'm getting when we enter wrong username

**Comment by sanyamjain04** [comment]
we have to send the `detail ` message when the username is incorrect

**Comment by dhruvdabhi101** [comment]
> we have to send the `detail ` message when the username is incorrect

and when the username is right.. we have to just send data.. right?

**Comment by sanyamjain04** [comment]
> and when the username is right.. we have to just send data.. right?

yes

**Comment by dhruvdabhi101** [comment]
- When we provide right username
Screenshot 2022-10-22 at 2 53 45 PM

- When we provide wrong username
Screenshot 2022-10-22 at 2 54 19 PM

**Review by sanyamjain04 — APPROVED** [review]
✅ LGTM
Thanks, @dhruvdabhi101  for contributing to Kubetweet. 👏🏻
__
Summary: 👌 This code looks good.

**Pull request merged**
